// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repository;

#nullable disable

namespace repository.Migrations
{
    [DbContext(typeof(DataProject))]
    partial class DataProjectModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("entities.AreasOfExpertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AreasOfExpertise");
                });

            modelBuilder.Entity("entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionReportingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Star")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("entities.PossibleTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskFeedbackId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskTypeIdId")
                        .HasColumnType("int");

                    b.Property<int?>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskFeedbackId");

                    b.HasIndex("TaskTypeIdId");

                    b.ToTable("PossibleTasks");
                });

            modelBuilder.Entity("entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonalAreasOfExpertiseId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAreasOfExpertiseId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("entities.PossibleTask", b =>
                {
                    b.HasOne("entities.Feedback", "TaskFeedback")
                        .WithMany()
                        .HasForeignKey("TaskFeedbackId");

                    b.HasOne("entities.AreasOfExpertise", "TaskTypeId")
                        .WithMany()
                        .HasForeignKey("TaskTypeIdId");

                    b.Navigation("TaskFeedback");

                    b.Navigation("TaskTypeId");
                });

            modelBuilder.Entity("entities.Volunteer", b =>
                {
                    b.HasOne("entities.AreasOfExpertise", "PersonalAreasOfExpertise")
                        .WithMany("ListVolunteer")
                        .HasForeignKey("PersonalAreasOfExpertiseId");

                    b.Navigation("PersonalAreasOfExpertise");
                });

            modelBuilder.Entity("entities.AreasOfExpertise", b =>
                {
                    b.Navigation("ListVolunteer");
                });
#pragma warning restore 612, 618
        }
    }
}
